import {Archivo_Black, Hind} from "next/font/google";
import "@/styles/globals.css"
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import BackToTopButton from "@/components/ui/BackToTopButton";

const fontText = Archivo_Black({
  variable: "--font-style",
  subsets: ["latin"],
  weight: '400',
});

const fontStyle = Hind({
  variable: "--font-text",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700']
});

export const metadata = {
  title: "PT Barry Siwi Mahardika",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontStyle.variable} ${fontText.variable} antialiased`}>
        <BackToTopButton/>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
